mkdir -p DH/integracao_aula_1e2/historia_da_contabilidade DH/integracao_aula_1e2/servidores DH/integracao_aula_1e2/interfaces_de_usuario DH/integracao_aula_1e2/infraestruturas DH/integracao_aula_1e2/o_que_faremos
touch DH/integracao_aula_1e2/historia_da_contabilidade/resumo.txt DH/integracao_aula_1e2/servidores/resumo.txt DH/integracao_aula_1e2/interfaces_de_usuario/resumo.txt DH/integracao_aula_1e2/infraestruturas/resumo.txt DH/integracao_aula_1e2/o_que_faremos/resumo.txt
ls -R
